'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header/header";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const posts = [
  {
    id: 1,
    name: "Who is it",
    img: "/mujik.png",
    created_at: "2025.01.03",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras facilisis mattis nunc, sed faucibus nibh feugiat at. Phasellus molestie lectus odio, dignissim tempor libero pellentesque vel. Vivamus a erat vel massa scelerisque tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce cursus diam eget purus pretium, eu tempor lacus finibus. Duis interdum sit amet lorem ac mollis. Aliquam eu faucibus ligula. Phasellus ultricies dictum porta. Vivamus non dapibus nunc. Aenean commodo sapien non tincidunt bibendum.",
    isLiked: false
  },
  {
    id: 2,
    name: "Gribu Chuvak",
    img: "/1.png",
    created_at: "2025.01.03",
    content: "some lopng text here",
    isLiked: false
  },
  {
    id: 3,
    name: "DB for Myalik Birthday",
    img: "/2.png",
    created_at: "2025.01.03",
    content: "some lopng text here",
    isLiked: false
  },{
    id: 4,
    name: "DB for Myalik Birthday",
    img: "/2.png",
    created_at: "2025.01.03",
    content: "some lopng text here",
    isLiked: false
  },{
    id: 5,
    name: "DB for Myalik Birthday",
    img: "/2.png",
    created_at: "2025.01.03",
    content: "some lopng text here",
    isLiked: false
  },{
    id: 6,
    name: "DB for Myalik Birthday",
    img: "/2.png",
    created_at: "2025.01.03",
    content: "some lopng text here",
    isLiked: false
  },{
    id: 7,
    name: "DB for Myalik Birthday",
    img: "/2.png",
    created_at: "2025.01.03",
    content: "some lopng text here",
    isLiked: false
  },{
    id: 8,
    name: "DB for Myalik Birthday",
    img: "/2.png",
    created_at: "2025.01.03",
    content: "some lopng text here",
    isLiked: false
  },{
    id: 9,
    name: "DB for Myalik Birthday",
    img: "/2.png",
    created_at: "2025.01.03",
    content: "some lopng text here",
    isLiked: false
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("posts", JSON.stringify(posts));
    }
  }, []);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Header />
       <div className="lg:px-[20%] sm:px-[0%] min-h-screen bg-[#1D0202]">
        {children}
       </div>
      </body>
    </html>
  );
}
